### ISSUE TITLE
Add pages please

### ISSUE THREAD

**Issue by reggi** [jackielii/simplest-redux-example#13]
```
git branch gh-pages
git push origin gh-pages
```

Then link to it in the description:

http://jackielii.github.io/simplest-redux-example

**Comment by reggi** [comment]
Also gotta add the bundle :)

**Comment by aowongster** [comment]
Hi,

I forked and made a github page here:

http://aowongster.github.io/simplest-redux-example/

I couldn't figure out how to make a PR to a non-existent branch.

https://github.com/aowongster/simplest-redux-example/tree/gh-pages

**Comment by jackielii** [comment]
@aowongster branch added, please send the PR, thanks!

**Comment by jackielii** [comment]
Just pushed it, also added the URL to the description. Thanks all, sorry took this long to get it done.
