### ISSUE TITLE
can't visit localhost:8000

### ISSUE THREAD

**Issue by Maplesog** [jackielii/simplest-redux-example#18]
![image](https://cloud.githubusercontent.com/assets/18155748/14167125/a577bc7e-f74b-11e5-9132-b328b2a46062.png)
![image](https://cloud.githubusercontent.com/assets/18155748/14167188/120bd74e-f74c-11e5-87d4-c7d2c276228f.png)

I'm new to redux ,and it got a situation that i post here when i type npm start .Can you give me some advice.

**Comment by jackielii** [comment]
It needs python to be installed for a simple http server.

When you run `npm start`, it runs `watchiy --extension=js -o bundle.js index.js` and put it in the background, then it run `python -m SimpleHTTPServer`

**Comment by Maplesog** [comment]
Finally, I use nginx instead ,and run it well

**Comment by jackielii** [comment]
Well done!

**Comment by yeze322** [comment]
This issue still exist, and I use `python -m SimpleHTTPServer` instead
