### ISSUE TITLE
Update babelify and include es2015 or react plugins

### ISSUE THREAD

**Issue by ismyrnow** [jackielii/simplest-redux-example#21]
Using version 7.3.0 of babelify, some functionality has been moved to plugins, which aren't included by default. Using that version of babelify, I had to do the following additional steps:

```
npm install --save-dev babel-preset-es2015 babel-preset-react
```

Then update the transform in the package.json:

``` json
"browserify": {
  "transform": [
    [ "babelify", { "presets": ["es2015", "react"] } ]
  ]
},
```

**Comment by jackielii** [comment]
fixed.
