### ISSUE TITLE
Errors on Mac OS

### ISSUE THREAD

**Issue by softweave** [jackielii/simplest-redux-example#22]
Running npm install resulted in this npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.20
3 info using node@v4.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart simplest-redux-example@0.0.0
6 info start simplest-redux-example@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info simplest-redux-example@0.0.0 Failed to exec start script
9 verbose stack Error: simplest-redux-example@0.0.0 start: `watchify --debug --extension=js -o bundle.js index.js & python -m SimpleHTTPServer`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid simplest-redux-example@0.0.0
11 verbose cwd /Users/ejane/Programming/react/simplest-redux-example-master
12 error Darwin 15.4.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.4.1
15 error npm  v2.14.20
16 error code ELIFECYCLE
17 error simplest-redux-example@0.0.0 start: `watchify --debug --extension=js -o bundle.js index.js & python -m SimpleHTTPServer`
17 error Exit status 1
18 error Failed at the simplest-redux-example@0.0.0 start script 'watchify --debug --extension=js -o bundle.js index.js & python -m SimpleHTTPServer'.
18 error This is most likely a problem with the simplest-redux-example package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     watchify --debug --extension=js -o bundle.js index.js & python -m SimpleHTTPServer
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs simplest-redux-example
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls simplest-redux-example
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by softweave** [comment]
I removed the scripts section before running 'npm install' and the installation was error free. I then restored scripts section back and successfully ran 'npm start'.

**Comment by jackielii** [comment]
glad you found a workaround, I don't have a Mac, so I'm going to leave this to someone with a MacOS to solve.

**Comment by aowongster** [comment]
I just did a clean install on OSX and it worked for me:

node: v6.1.0
npm: 3.8.6

in line 1: it looks like the command invoked was `npm start`
in line 7: it looks like the command was called under root

**Comment by softweave** [comment]
After upgrading node to the latest LTS versions:
node: v4.4.4
npm: 2.15.1
reinstalling from scratch completed without errors. Apologies for not doing this in the first place.
