### ISSUE TITLE
Python server in "npm start"

### ISSUE THREAD

**Issue by firasd** [jackielii/simplest-redux-example#23]
Thanks for this great example, it helped me finally understand how to use Redux (especially the ES5 example.)

However, I couldn't run it on my system because of the python dependency. Just thought I'd bring this up in case this example can run off a node server, especially as it's aimed towards beginners.

**Comment by jackielii** [comment]
Yes, I thought about it, but decided against as it brings in another dependency and also as python is widely available.

If you make a example in a branch, I'll be happy to accept it.

**Comment by firasd** [comment]
Alright, thanks. Closing this for now.
