### ISSUE TITLE
请教个问题，关于返回的state是否需要是新对象？

### ISSUE THREAD

**Issue by Skypow2012** [jackielii/simplest-redux-example#40]
simplest-redux-example/index.js:35
这个counter函数的default是不是返回一个新的state会比较好？比如return {...state}

**Comment by jackielii** [comment]
> simplest-redux-example/index.js:35
> 这个counter函数的default是不是返回一个新的state会比较好？比如return {...state}

正确的方式是返回原来的state, 很少的情况要clone一个新的state返回
